/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.tayi.view;

import id.tayi.App;
import id.tayi.controller.UserController;
import id.tayi.model.MainPage;
import id.tayi.model.ScenePage;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.image.Image;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;

public class LoginPage implements MainPage, ScenePage{
    private App app;
    private Scene scene;
    private UserController userDAO = new UserController();

    public LoginPage(App app){
        this.app = app;
        initialize();
    }

    public void initialize(){
        Label desc = new Label("Selamat datang di aplikasi kami.");
        Label info = new Label();
        Label merek = new Label("BuangKit");
        Button masuk = new Button("Masuk");
        Button daftar = new Button("Daftar");
        CheckBox peek = new CheckBox();
        ImageView logo = new ImageView(new Image(getClass().getResource("/images/logo2.png").toExternalForm()));
        TextField passUp = new TextField();
        TextField username = new TextField();
        PasswordField password = new PasswordField();
        StackPane passs = new StackPane(passUp, password, peek);
        StackPane.setAlignment(peek, Pos.CENTER_RIGHT);
        StackPane.setMargin(peek, new Insets(0,10,0,0));
        VBox input = new VBox(logo, merek, desc, username, passs, masuk, daftar);
        StackPane root = new StackPane(input, info);
        StackPane.setMargin(info, new Insets(260, 0, 0, 0));
        scene = new Scene(root, 1366, 693);
        
        passUp.setPromptText("Password");
        password.setPromptText("Password");
        username.setPromptText("Username");

        input.setId("input");
        masuk.setId("masuk");
        merek.setId("buangkit");
        root.setId("background");
        info.getStyleClass().add("info");
        desc.getStyleClass().add("teks");
        passUp.getStyleClass().add("field");
        masuk.getStyleClass().add("button");
        daftar.getStyleClass().add("button");
        username.getStyleClass().add("field");
        password.getStyleClass().add("field");
        peek.getStyleClass().add("custom-checkbox");
        logo.setFitWidth(100);
        logo.setFitHeight(100);
        passUp.setFocusTraversable(false);
        username.setFocusTraversable(false);
        password.setFocusTraversable(false);

        passUp.setVisible(false);
        peek.setOnAction(e -> {
            if (password.isVisible()) {
                passUp.setText(password.getText()); 
                passUp.setVisible(true);
                password.setVisible(false);
            } else {
                password.setText(passUp.getText()); 
                password.setVisible(true);
                passUp.setVisible(false);
            }
        });

        masuk.setOnAction(e ->{
            String nama = username.getText();
            String pass = password.getText();
            if(userDAO.checkLogin(nama, pass).equals("done")){
                app.showDefaultPage();
            } else {
                info.setText(userDAO.checkLogin(nama, pass));
                info.setVisible(true);
            }
        });

        daftar.setOnAction(e ->{
            app.showRegisterPage();
        });

        root.setAlignment(Pos.CENTER);
        scene.getStylesheets().add(getClass().getResource("/style/style.css").toExternalForm());
    }

    public Scene getScene(){
        return this.scene;
    }

}
